name: Build and Push News Images
on:
  push:
    branches:
      - master
    paths:
      - news
  repository_dispatch:

env:
  ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT }}
  AWS_REGION:     ${{ vars.AWS_DEFAULT_REGION }}
  REGISTRY:       ${{ vars.REGISTRY }}
  REPOSITORY:     ${{ vars.REPOSITORY_NEWS_IMAGE }}

jobs:
  BuildPushBaseImage:
    runs-on: ubuntu-latest
    environment: News Feed - Dev
    env:
      GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/ECRPushImage
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR Credentials
        id: ecr-credentials
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Release
        id: tag-release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Build, Tag and Push
        env:
          VERSION: ${{ steps.tag-release.outputs.tag_name }}
        run: |
          docker build -f base/Dockerfile base \
          -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:$VERSION \
          -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest && \
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }} --all-tags