name: Build and push base image
on:
  push:
    branches:
      - master
  repository_dispatch:
jobs:
  BuildPushBaseImage:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::128684785872:role/ECRPushImage
          aws-region: $AWS_DEFAULT_REGION

      - name: ECR Credentials
        id: ecr-credentials
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push
        run: |
          docker build -f base/Dockerfile base -t $REGISTRY_NEWS_FEED/$REPOSITORY_NEWS_FEED:latest
          docker push $REGISTRY_NEWS_FEED/$REPOSITORY_NEWS_FEED:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT