name: Build and Push Base Image
on:
  push:
    branches:
      - master
    paths:
      - base
  workflow_dispatch:

jobs:
  BuildPushBaseImage:
    runs-on: ubuntu-latest
    environment: Development
    env:
      GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ECRPushImage
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: ECR Credentials
        id: ecr-credentials
        uses: aws-actions/amazon-ecr-login@v1

      - name: Tag Release
        id: tag-release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Build, Tag and Push
        env:
          VERSION: ${{ steps.tag-release.outputs.tag_name }}
        run: |
          docker build -f base/Dockerfile base \
          -t ${{ vars.REGISTRY }}/${{ vars.REPOSITORY_BASE_IMAGE }}:$VERSION \
          -t ${{ vars.REGISTRY }}/${{ vars.REPOSITORY_BASE_IMAGE }}:latest && \
          docker push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY_BASE_IMAGE }} --all-tags